import { db } from "./db";
import { properties } from "@shared/schema";
import { sql } from "drizzle-orm";

const seedProperties = [
  {
    title: "Luxury Villa in F-7",
    description: "Stunning 5-bedroom luxury villa in the prestigious F-7 sector. Features Italian marble flooring, a private swimming pool, manicured gardens, and state-of-the-art security systems. Perfect for families seeking the finest living experience in Islamabad.",
    price: 85000000,
    type: "Villa",
    status: "For Sale",
    location: "F-7, Islamabad",
    city: "Islamabad",
    area: 8000,
    bedrooms: 5,
    bathrooms: 6,
    image: "/images/property-1.png",
    featured: true,
    amenities: ["Swimming Pool", "Garden", "Garage", "Security System", "Central Heating", "Servant Quarter"],
  },
  {
    title: "Modern Apartment in F-10",
    description: "Contemporary 3-bedroom apartment with panoramic views of Margalla Hills. Open-plan living with floor-to-ceiling windows, fully equipped modern kitchen, and access to building amenities including gym and rooftop terrace.",
    price: 25000000,
    type: "Apartment",
    status: "For Sale",
    location: "F-10, Islamabad",
    city: "Islamabad",
    area: 2200,
    bedrooms: 3,
    bathrooms: 3,
    image: "/images/property-2.png",
    featured: true,
    amenities: ["Gym", "Rooftop Terrace", "Parking", "Elevator", "Central Air", "Security"],
  },
  {
    title: "Elegant Townhouse in F-11",
    description: "Beautifully designed 4-bedroom townhouse in the quiet F-11 neighborhood. Features a spacious living room, modern kitchen, landscaped front yard, and a dedicated parking area. Close to schools and markets.",
    price: 45000000,
    type: "Townhouse",
    status: "For Sale",
    location: "F-11, Islamabad",
    city: "Islamabad",
    area: 3500,
    bedrooms: 4,
    bathrooms: 4,
    image: "/images/property-3.png",
    featured: true,
    amenities: ["Garden", "Parking", "Servant Quarter", "Study Room", "Laundry Room"],
  },
  {
    title: "Commercial Office Space in Blue Area",
    description: "Premium commercial office space in Islamabad's central business district. Open floor plan suitable for corporate offices, IT companies, or co-working spaces. High-speed internet infrastructure and backup power.",
    price: 120000,
    type: "Commercial",
    status: "For Rent",
    location: "F-7, Islamabad",
    city: "Islamabad",
    area: 5000,
    bedrooms: null,
    bathrooms: 4,
    image: "/images/property-4.png",
    featured: true,
    amenities: ["Parking", "Elevator", "Backup Power", "Conference Room", "Kitchen", "Security"],
  },
  {
    title: "Luxury Penthouse in DHA",
    description: "Exclusive penthouse apartment in DHA Phase 2 with breathtaking city views. Features a private rooftop terrace, jacuzzi, designer interiors, and smart home automation. The epitome of luxury living.",
    price: 65000000,
    type: "Penthouse",
    status: "For Sale",
    location: "DHA, Islamabad",
    city: "Islamabad",
    area: 4500,
    bedrooms: 4,
    bathrooms: 5,
    image: "/images/property-5.png",
    featured: true,
    amenities: ["Jacuzzi", "Rooftop Terrace", "Smart Home", "Gym", "Concierge", "Parking"],
  },
  {
    title: "Traditional House in Bahria Town",
    description: "Charming 6-bedroom family house in Bahria Town with traditional Pakistani architectural elements. Spacious courtyard, separate guest wing, and proximity to commercial areas and parks.",
    price: 38000000,
    type: "House",
    status: "For Sale",
    location: "Bahria Town, Islamabad",
    city: "Islamabad",
    area: 5500,
    bedrooms: 6,
    bathrooms: 5,
    image: "/images/property-6.png",
    featured: true,
    amenities: ["Courtyard", "Guest Wing", "Garden", "Garage", "Servant Quarter", "Mosque Nearby"],
  },
  {
    title: "Modern Duplex in DHA Lahore",
    description: "Sleek 3-bedroom duplex in DHA Phase 5, Lahore. Minimalist design with high ceilings, imported fittings, and a two-car garage. Located in a gated community with 24/7 security.",
    price: 32000000,
    type: "House",
    status: "For Sale",
    location: "DHA, Lahore",
    city: "Lahore",
    area: 3000,
    bedrooms: 3,
    bathrooms: 3,
    image: "/images/property-7.png",
    featured: false,
    amenities: ["Garage", "Security", "Park Facing", "Modern Kitchen", "Terrace"],
  },
  {
    title: "Furnished Apartment in Gulberg",
    description: "Fully furnished luxury 2-bedroom apartment in Gulberg, Lahore. Walking distance to MM Alam Road, shopping centers, and restaurants. Ideal for professionals or couples.",
    price: 85000,
    type: "Apartment",
    status: "For Rent",
    location: "Gulberg, Lahore",
    city: "Lahore",
    area: 1800,
    bedrooms: 2,
    bathrooms: 2,
    image: "/images/property-8.png",
    featured: false,
    amenities: ["Furnished", "Parking", "Security", "Gym", "Balcony", "Central Air"],
  },
  {
    title: "Family Home in F-10",
    description: "Spacious 5-bedroom family home with separate drawing and dining rooms, large kitchen, and a lush backyard garden. Quiet cul-de-sac location perfect for families with children.",
    price: 55000000,
    type: "House",
    status: "For Sale",
    location: "F-10, Islamabad",
    city: "Islamabad",
    area: 6000,
    bedrooms: 5,
    bathrooms: 5,
    image: "/images/property-1.png",
    featured: false,
    amenities: ["Garden", "Garage", "Servant Quarter", "Study", "Security", "Central Heating"],
  },
  {
    title: "Studio Apartment in Bahria Town Lahore",
    description: "Modern studio apartment in Bahria Town, Lahore. Perfect for singles or young professionals. Fully equipped kitchenette, modern bathroom, and access to community amenities.",
    price: 35000,
    type: "Apartment",
    status: "For Rent",
    location: "Bahria Town, Lahore",
    city: "Lahore",
    area: 600,
    bedrooms: 1,
    bathrooms: 1,
    image: "/images/property-5.png",
    featured: false,
    amenities: ["Furnished", "Security", "Community Pool", "Gym", "Parking"],
  },
];

export async function seedDatabase() {
  const existing = await db.select({ id: properties.id }).from(properties).limit(1);
  if (existing.length > 0) {
    console.log("Database already seeded, skipping...");
    return;
  }

  console.log("Seeding database with properties...");
  for (const prop of seedProperties) {
    await db.insert(properties).values(prop);
  }
  console.log(`Seeded ${seedProperties.length} properties.`);
}
